site_name: 'prod-test'
site_description: 'Main documentation for the prod-test'
repo_url: https://github.com/hsenagr/prod-test
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'
